apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-config
data:
  default.topic.partitions: "2"
  default.topic.replication.factor: "2"
  bootstrap.servers: kafka-sebi-avat6ar.c.aivencloud.com:18981
  auth.secret.ref.name: broker-secret