kafka.bootstrap.servers=kafka-sebi-avat6ar.c.aivencloud.com:18981
kafka.security.protocol=SSL
kafka.ssl.protocol=TLS
kafka.ssl.key.password=safePassword123
%prod.kafka.ssl.keystore.location=/etc/certs/client.keystore.p12
kafka.ssl.keystore.location=/Users/sebastienblanc/sail/serverless-creative-writer/client.keystore.p12
kafka.ssl.keystore.password=safePassword123
kafka.ssl.keystore.type=PKCS12
%prod.kafka.ssl.truststore.location=/etc/certs/client.truststore.jks
kafka.ssl.truststore.location=/Users/sebastienblanc/sail/serverless-creative-writer/client.truststore.jks
kafka.ssl.truststore.password=safePassword123
kafka.ssl.truststore.type=JKS

%dev.quarkus.http.port=8081
quarkus.kubernetes.mounts.certs-volume.path=/etc/certs
quarkus.kubernetes.secret-volumes.certs-volume.secret-name=agents-kafka-secrets
quarkus.kubernetes.secret-volumes.certs-volume.items.keystore.path=client.keystore.p12
quarkus.kubernetes.secret-volumes.certs-volume.items.truststore.path=client.truststore.jks