prompt.user=You are a generic AI agent saying hello and replying using the tools at your disposal.
prompt.system=You are a helpful AI agent.

quarkus.langchain4j.mcp.sail.transport-type=http
quarkus.langchain4j.mcp.sail.url=http://localhost:8081/mcp/sse
